# Generated by Django 4.2.20 on 2025-04-29 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_1', models.ImageField(upload_to='listing-images/')),
                ('image_2', models.ImageField(blank=True, upload_to='listing-images/')),
                ('image_3', models.ImageField(blank=True, upload_to='listing-images/')),
                ('title', models.CharField(max_length=40)),
                ('phone', models.PositiveIntegerField(blank=True, default=0)),
                ('description', models.TextField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(choices=[('AddisKetema', 'Addis Ketema'), ('AkakyKaliti', 'Akaky Kaliti'), ('Arada', 'Arada'), ('Bole', 'Bole'), ('Gullele', 'Gullele'), ('Kirkos', 'Kirkos'), ('KolfeKeranio', 'Kolfe Keranio'), ('Lideta', 'Lideta'), ('NifasSilkLafto', 'Nifas Silk-Lafto'), ('Yeka', 'Yeka')], max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold')], default='active', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('listing', 'user')},
            },
        ),
    ]
